### ISSUE TITLE
Portkey with Self-hosted LLMs in VM?

### ISSUE THREAD

**Issue by AIAnytime** [Portkey-AI/portkey-cookbook#66]
Hi, I just wanted to check if Portkey is compatible if I have my LLM privately hosted within a VM. I can't use Mistral API from Mistral Cloud or anywhere else?

**Comment by vrushankportkey** [comment]
Hey @AIAnytime **yes** you can use Portkey with your privately hosted LLM! Check out these docs: https://portkey.ai/docs/welcome/integration-guides/byollm

You can use the `custom_host` property to change the base URL for Mistral API to your VM URL. - https://portkey.ai/docs/product/ai-gateway-streamline-llm-integrations/universal-api#integrating-local-or-private-models

Please let me know if this is helpful. We should also make a cookbook on this!
